FROM node:10-buster AS base

RUN ["apt-get", "install", "gcc-8", "g++-8"]

WORKDIR /usr/src/app

COPY binaryDependencies ./binaryDependencies
COPY package.json ./

RUN "yarn"

ENV NODE_ENV development
CMD [ "yarn", "nodemon" ]
